namespace Domain.Tasks.Enums;

public enum EventType
{
    OPENED,
    CLOSED,
    ISSUE_ASSIGNED,
    ISSUE_UNASSIGNED,
    MILESTONE_ASSIGNED,
    MILESTONE_UNASSIGNED,
    PULL_REQUEST_MERGED,
    PULL_REQUEST_ASSIGNED,
    PULL_REQUEST_UNASSIGNED,
    PULL_REQUEST_ISSUE_ADDED,
    PULL_REQUEST_ISSUE_REMOVED
}