# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["feature/docker-setup"]
  pull_request:
    branches: ["feature/docker-setup"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Execute tests
        run: |
        docker exec -it web_api /bin/bash
        dotnet test Tests.dll

      - name: Build and Push Docker Images
        run: |
          echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
          docker-compose build
          docker-compose push

        env:
          CONNECTION_STRING: ${{secrets.CONNECTION_STRING}}
          SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}
          JWT_KEY: ${{secrets.JWT_KEY}}
          POSTGRES_USER: ${{secrets.POSTGRES_USER}}
          POSTGRES_PASSWORD: ${{secrets.POSTGRES_PASSWORD}}
          POSTGRES_DB: ${{secrets.POSTGRES_DB}}
