# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["feature/docker-setup"]
  pull_request:
    branches: ["feature/docker-setup"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Create env file
        run: |
          touch .env
          echo "${{ secrets.ENV }}" >> .env

      - name: Start containers
        run: docker-compose -f "docker-compose.yml" up -d --build

      - name: Execute tests
        run: |
          docker exec web_api dotnet test Tests.dll

      - name: Stop containers
        run: docker-compose -f "docker-compose.yml" down
