# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: ["feature/docker-setup"]
  pull_request:
    branches: ["feature/docker-setup"]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Docker
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and Push Docker Images
        run: |
          docker login -u ${{secrets.DOCKERHUB_USERNAME}} -p ${{secrets.DOCKERHUB_PASSWORD}}
          docker-compose build
          docker-compose push

        env:
          CONNECTION_STRING: ${{secrets.REPO_DATABASE_KEY}}
          SENDGRID_API_KEY: ${{secrets.SENDGRID_API_KEY}}
